### ISSUE TITLE
PRCI - Request Progress Indicator

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#10]
![image](https://user-images.githubusercontent.com/45305362/179524346-b6329ef1-e09f-4639-ac3f-dfccd3a8dd68.png)

**Comment by m4rk055** [comment]
There is a [similar component](https://github.com/blindnet-io/privateform-web-client/tree/main/src/app/components/gdpr-request-status-steps) in PF, try to reuse the HTML/CSS.

**Comment by jboileau99** [comment]
Removed from prci sketches
