### ISSUE TITLE
Default target wrong

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#105]
![image](https://user-images.githubusercontent.com/317424/188634396-128aa0b9-591f-4c10-929f-0164300ed66a.png)

The target selected by default is System. Yet in [PRIV](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#targets), `PARTNERS` is the default value.

**Comment by jboileau99** [comment]
@milstan That selection is a provenance restriction for a particular demand, not the target of the entire privacy request. Based on [this section](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/RFC-PRIV.md#provenance-restriction) of PRIV I used system as the default.

For the target of the whole privacy request, that option is available afterwords in the review view (with partners as the default):

![Screenshot from 2022-09-06 15-29-02](https://user-images.githubusercontent.com/45305362/188648408-7d82f1f2-2ef7-4c28-a338-699cd5b02b9c.png)

It is designed this way to accomadate for multiple demands in a single request (each of which may have a different provenance restriction, defaulting to system), then all of these demands will be shown in the request review view and the user may select a target for the whole request:

![ACCESS 5 (review)](https://user-images.githubusercontent.com/45305362/188651125-bbe93439-ce05-44fa-b362-c9fa00ff0ed6.png)

**Comment by milstan** [comment]
Indeed, you are right Justin. Thanks for the detailed response.
