### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#14]
Developers must be able to configure whether our component will prompt the user for authentication before or after the request, for each demand type. See blindnet-io/product-management#814

**Comment by jboileau99** [comment]
@milstan @m4rk055 From our dicussion last week regarding authentication, specifically the [a priori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-priori-authentication) and [a posteriori](https://github.com/blindnet-io/product-management/blob/main/refs/schemas/priv/scenarios.md#a-posteriori-authentication) cases, I realize I may have misunderstood it originally when working on the sketches.

I currently plan for it to look something like [this](https://www.figma.com/file/miUd9PEmLrjut53rwrQViX/Privacy-request-capture-service?node-id=1258%3A386), depending on the two different auth cases. However, I didn't think the request was actually submitted in the a posteriori case until the user logged in - but as @milstan explained, the request should be submitted and then the authentication is requested.

So, I'm thinking perhaps the a posteriori case is better handled through the status view. I.e. a user submits their request, is brought to the status page which displays in processing, and then once the the request is processed the state switches to require_authentication, then the PRCI will show a status indicating this and the user can then authenticate within the PRCI via the methods configured. @m4rk055 Is this how you imagine it working?

**Comment by m4rk055** [comment]
I haven't given it much thought yet.
What you described works when authentication is immediately requested but gets tricky when auth request arrives asynchronously (could take days e.g.) - how is the data subject then notified?
When e.g. an unauthenticated ACCESS request is made, what exactly are the possible workflows to authenticate?
@milstan talked about one way to authenticate - by a third party service that requests and verifies users' identity documents.

If a data subject is authenticated outside of PRCI, it's weird to request them to open the request status page to get authenticated in the devkit.
In that case, it's probably better for the server to provide the data subject's identity to the PCE directly (new API endpoint).

This is quite a complex issue and requires more information.

**Comment by milstan** [comment]
for a posteriori authentication, I like the idea of status page showing - pending authentication. Let us say that the Client system is responsible, in this case, to promt the user to authenticate, and let the devkit know when the user has been authenticated. At that point the satus page changes, and processing can begin.

So the status page would only be responsable for whoing "pending authentication" status, and not necessairly promting the user to authenticate.

I agree it's a complex issue, but we can also consider this to be a good enough current solution.
