### ISSUE TITLE
Add authentication to demo

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#155]
- [x] Use a auth0 [magic link](https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-magic-link)
- [x] Make PRCI accept a token and pass this in the auth header of all requests

**Comment by milstan** [comment]
@jboileau99 this seems done. Close?

**Comment by jboileau99** [comment]
> @jboileau99 this seems done. Close?

@milstan Indeed, thanks for the reminder
