### ISSUE TITLE
Back button on submission page

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#178]
## Description

The last page of PRCI, where the submit button is, has no way of going back

![image](https://user-images.githubusercontent.com/317424/197572888-084f0728-9ad9-4535-8d46-a96e6883f965.png)

### Intended outcome

Include a button to allow going back if the user made an error.

**Comment by Clementinev** [comment]
This is something we discussed with @jboileau99 , would it be possible technically to have a back button "remembering" which demand has last been open/modified in case of multiple demands? 
If not, in case of multiple demands what do you think of the back button opening the last demand that has been created?

**Comment by milstan** [comment]
We'll here we are clearly in a mono-demand scenario. So in this case, it is clear.

The request with multiple demands is for later (and yes, there it would make sense to allow deleting demands, and all them to go back to first screen to make new demands).

**Comment by jboileau99** [comment]
@milstan I believe what you're describing is what the edit (pencil) button does now, when clicked it should re-open the demand with the data they entered previously. I guess this is a good indicator that it's not obvious what that button does. 

In the new version, it looks like this:

![image](https://user-images.githubusercontent.com/45305362/198259999-78706c6b-5787-438c-9798-8574e22b7dec.png)

The user can click the pencil + paper icon (beside 'ACCESS Demand') and that will bring them back to the demand form where they can change what they entered. What do you think of this?

**Comment by milstan** [comment]
It is more obvious now but I still think the user would feel like they can't go back as they are in a mono-demand scenario. 

Maybe a solution could be including (next to the SUBMIT button) a button that says "CANCEL AND GO BACK TO START" that deletes all demands and lets them start from strach?

I am not sure what is the best solution, but I think as long as there is only one button in the bottom, there will be frustration.

**Comment by Clementinev** [comment]
What do you think of something like this : 
1. having a more visible and explicit modify button + having a "Cancel Request" button at request review screen (at the demand back button place) with a warning message associated if clicked 
![Request Review - Summary Open](https://user-images.githubusercontent.com/89908145/198644823-e14e54af-643f-4c7b-9262-7b625f93c90f.png)

2. or adding just the "Cancel Request" button at request review screen (at the demand back button place) with a warning message associated if clicked : 
![Request Review - Summary Open2](https://user-images.githubusercontent.com/89908145/198649607-c259a2fd-8ef0-40fd-8812-99468898e017.png)

**Comment by milstan** [comment]
I like the 2

**Comment by jboileau99** [comment]
I like 2 also, thanks @Clementinev. I'll add that
