### ISSUE TITLE
PRCI - Enforce Minimal Decision Principle

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#20]
We have the [Minimal Decision Principle](https://github.com/blindnet-io/product-management/blob/main/refs/Product-design-principles.md#2-minimal-decision-principle).

We need it applied in PRCI. Clearly it is not applied if we take a look here:
![Untitled](https://user-images.githubusercontent.com/317424/180475705-4012f8af-e2ab-4210-a226-1be7f2ea504b.jpg)

The user, having chosen to make a TRANSPARENCY request is given a choice (again) of other requests. This information MUST be hidden.

The principle is violated in other places too. E.g. for the TRASNPARENCY demand it is reasonable to assume the user wants to set `TRANSAPRENCY` and not any of the subcategories, unless the user explictely wants to specify it. SO the interface MUST pre-select `TRANSPARENCY` and only offer the option to go into `TRANSPARENCY.*` specific choices.

Also it should be possible for Systems to configure a subset of demands they allow. So it is important not to show demands that are not supported (the checkboxes currently shown but disabled)

**Comment by jboileau99** [comment]
> Also it should be possible for Systems to configure a subset of demands they allow. So it is important not to show demands that are not supported (the checkboxes currently shown but disabled)

This actually is included in the component already, via the "actions" attribute - see this [storybook example](https://blindnet-io.github.io/privacy-components-web/?path=/story/bldnprivrequest--custom-actions)

**Comment by milstan** [comment]
Great. Thanx
