### ISSUE TITLE
PRCI - Simple Back Button

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#21]
There should be a back button at every step (until I finally submit the request), so when I see the confirmation screen I might realize I want to tick some more checkboxes and go back.

**Comment by jboileau99** [comment]
This functionality is acheived through the edit button in the demand review screen and the back button in the demand edit screen. The first version of the back button in the edit screen will simply bring the user back to the action menu. A later version (#61) will function more as an undo for individual changes within the action form.
