### ISSUE TITLE
PRCI - Remove OTHER DEMAND button

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#23]
Remove OTHER DEMAND button. We want to make id difficult for the user to make any demand that is not expressed in predefined PRIV terms (and that requires fully manual processing).

Instead, at the bottom include a smaller and very pale text like "Want to make some other demand? Click here but be prepared to wait longer"

**Comment by noelmace** [comment]
@Clementinev & @jboileau99 I see this issue has an "in review" status but I don't see any linked PR or issue.
Please either update the status or add the links (reminded: to indicate a PR "solves" an issue, just use the "close" keyword).

**Comment by Clementinev** [comment]
https://github.com/blindnet-io/product-management/issues/853

**Comment by noelmace** [comment]
So, if I understand correctly, https://github.com/blindnet-io/product-management/issues/853 track the design making for this issue, not development. If it's the case, this issue should still be in the backlog state, as this project is here to track development, and design is a prerequisite to move an issue to the ready state.

**Comment by noelmace** [comment]
Sorry, I was using the mobile app and it didn't show this change, my bad 😅

**Comment by Clementinev** [comment]
But I notice even on desktop it seems that the change of state is not showing on the issues thread as it used to show on "classic" project

**Comment by noelmace** [comment]
Indeed. But it is likely to be fixed very soon (https://github.com/github/roadmap/issues/483 planned for Q3 2002, so before September).
