### ISSUE TITLE
[PRCI - demo] info icon missing on privacy scope 

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/privacy-components-web#269]
On the demo, on PRCI, the info icon is missing for the privacy scope (for object and restrict request): 
<img width="1438" alt="Screenshot 2022-12-06 at 14 50 52" src="https://user-images.githubusercontent.com/89908145/205948467-b8d964ec-f9f3-46b7-ac3f-7c452c529eea.png">

**Comment by jboileau99** [comment]
@Clementinev Do you still not see it in the demo, I updated it this morning and now I see the icon.. but maybe it's only missing on safari?

**Comment by Clementinev** [comment]
Thank you @jboileau99 it's all good now (on chrome and on safari) so we can close this issue
