### ISSUE TITLE
[Privacy portal - demo] target options

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/privacy-components-web#281]
Following our discussion at desko and https://github.com/blindnet-io/privacy-components-web/issues/210

On the dem, on PRCI, on the target options :

- The definitions should be the previous ones below : 
<img width="400" alt="201111029-44fcb570-4dde-4499-b496-bcc3def7d935" src="https://user-images.githubusercontent.com/89908145/207059687-c768156a-1fec-4431-b5a1-9c059a111f3a.png">

- "All target" option should be deleted as it is already there with the default option "This system, all systems within this organization and all partners systems where data has been shared or obtained"

**Comment by m4rk055** [comment]
I think it's done
