### ISSUE TITLE
[demo - prize draw] move the confirmation message down the screen

### ISSUE THREAD

**Issue by Clementinev** [blindnet-io/privacy-components-web#283]
On the demo, on the prize draw part, the feedback message confirming that the participation has been recorded 
<img width="300" alt="prize 1" src="https://user-images.githubusercontent.com/89908145/207330150-f52bbfb8-a71f-44c0-a097-cffff5568f37.png">
is at the top of the screen and is non visible if the screen is scrolled down, can lead the user wondering if the button has been clicked correctly, if the the form has been submitted correctly  

The confirmation message should be at the bottom of the screen under the buttons so the user can see right away that the entry is submitted without having to scroll up

<img width="1440" alt="prize2" src="https://user-images.githubusercontent.com/89908145/207330003-911088a2-5ce6-4aac-980e-83f4cd52b0d1.png">

**Comment by m4rk055** [comment]
Done

**Comment by Clementinev** [comment]
Thanks works well
