### ISSUE TITLE
[DCI] Initialize DCI web component

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/privacy-components-web#34]
Initialize the associated web component.

This isn't blocked by #33, as the web component can be created in the project as it is, with associated storybook stories, and transferred to a dedicated package as part of #33.

**Comment by milstan** [comment]
@jboileau99 please note that the clients Systems should be able to use components independtly. Meaning a system can use PRCI without using DCI (example: [DPO COnsulting](https://github.com/blindnet-io/clients-management/issues/62) has their own app for DCI and would only use PRCI to gather requests, authenticate the data subjects, and show answers, but would import privacy requests to their MyDPO app that serves as their own DCI)

It is probably what you had in mind anyway, I'm giving you the info just in case.

**Comment by jboileau99** [comment]
@milstan Yes that's what I had in mind, but good to confirm and frame in terms of the use case. Thanks :)
