### ISSUE TITLE
PRCI - Localization

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#7]
https://lit.dev/docs/localization/overview/

**Comment by jboileau99** [comment]
@Clementinev To add the translations, edit [this file](https://github.com/blindnet-io/privacy-components-web/blob/localization/xliff/fr.xlf) on the localization branch and add a `<target>{translated text here}</target>` under the `<source>` tag for each word/phrase.

**Comment by milstan** [comment]
For purposes of Privacy Requests answers (later in DCI) we'll also need translations of all the PRIV terms, and their descriptions. But also here, if the user wants to restrict its request to a particular privacy scope, we'll need PRIV Data Category Terms, Processing Categorie Terms, Purpose Terms...

Would it make sense to have a cross-compoment localilasion file for all PRIV terms, where for each RPVI term in each language there is a Label and Description (like priv:`ACCESS` - "Access", "Access the data system has on you")? 

I mean still in this lit format? I don't suggest to change anything here to the way you'r approaching localisation - it is great. Just suggesting we might need additional content localised, and that some of it is cross-component.

**Comment by jboileau99** [comment]
@milstan You're right - a lot of our localized content will be cross-component. I've been thinking about how we could share it between components, perhaps a separate repo with the localization dictionaries that all the components have as a submodule? We would probably have to dig deeper into the config options for lit-localize to get this to work right. @noelmace thoughts?

**Comment by noelmace** [comment]
As discussed, this is only a web frontend matter, so we don't need to share this between several repositories as the code sharing will be addressed during the transition to a "monorepo".
