### ISSUE TITLE
Implement PRIV Types from openAPI Schema

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#8]
Automatically generate typescript types from our open API schema.

- All models should be stored in the @blindnet/core package

**Comment by milstan** [comment]
This file should directly replace the [dictionary file](https://github.com/blindnet-io/product-management/tree/main/refs/schemas/priv/dictionary/actions) Clémentine and I made. No need to keep our format - we didn't really knwo what would be usefull. What you have here is good.

Just no need to have two. Simply replace the old one with this.

**Comment by noelmace** [comment]
If we opt for using Stoplight/Prism and write OpenAPI definitions, those can be directly generated using something like https://github.com/drwpow/openapi-typescript

**Comment by milstan** [comment]
@jboileau99 with regards to the responses to privacy requests, like this one

> {
>   "response-id": "6c0dd4b4-4814-4883-84c0-9864e85fecff",
>   "in-response-to": "79d0b652-183e-47f5-ac37-35227fee4cf8",
>   "date": "2019-08-24T14:15:22Z",
>   "system": "http://example.com",
>   "requested-action": "TRANSPARENCY.POLICY",
>   "data-subject": {
>     "dsid-schema": "string",
>     "dsid": "string"
>   },
>   "status": "GRANTED",
>   "motiv": "VALID-REASONS",
>   "answers": "string",
>   "message": "string",
>   "lang": "en",
>   "includes": [
>     null
>   ],
>   "data": {}
> }

Please note that when the request is granted, there is no need to giving a motive. Motive is optional - and expected when the request is not GRANTED.

I updated PRIV with this note in the latest update.

**Comment by jboileau99** [comment]
@milstan When a privacy request contains more than one demand, will there be a privacy response for each demand (identified by demand-id)? This is how I interpreted it from the [priv spec](https://github.com/blindnet-io/product-management/blob/priv-event/refs/schemas/priv/RFC-PRIV.md#privacy-request-response), but wanted to make sure

**Comment by milstan** [comment]
There will be one Response for the Privacy Request (`in-response-to`: request ID), that will have for `incldues` multiple Privacy Request Responses, each having for `in-response-to` the `demand-id` to which they are the reponse.

It's a nested structure.

Also, in the context of coordinated responses. A Repnse made to a particular demand can also include other resposnes (to the same demand) made other systems.

**Comment by milstan** [comment]
It should have mutpile nested response. For each of those it should have a unique `data` or `message` that responds to the particular demand.

**Comment by jboileau99** [comment]
Discussed new response structure with @m4rk055, will update stoplight on Monday

**Comment by jboileau99** [comment]
Moved this to milestone v0.5. The request + response structure will change very often in the early stages of development, so it's easier initially to manually define and modify the types.
