### ISSUE TITLE
Handle (re)fetching request status

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#92]
> (actually on line 116, so to solve later on)
> 
> Making a request every 3 seconds is a very bad approach here IMHO. It won't scale. Remember you should always try to make as few requests as possible. This request should be triggered by the user, directly (i.e. reload button) or indirectly (i.e. loading the view) to determine with @Clementinev. Alternatively, you could use a web socket if really necessary, but I don't think it is here (to discuss with @m4rk055).

_Originally posted by @noelmace in https://github.com/blindnet-io/privacy-components-web/pull/87#discussion_r961398410_

We must choose a better way to fetch the requests list and statuses for demands in a request. Options are:
1. Only fetch when the request list or demand status view is loaded
2. Include a reload button
3. Web socket

I think (2) is a better choice than (1), because:
- If we don't include a reload button, a user that wants to reload the request or status page will just navigate within the component (e.g. back to the menu and then return to the requests page) to achieve a reload, which is a bad user experience
- We can make the reload button clickable once every X seconds to  prevent the user from flooding the server with requests by spamming the button

As for (3), I've only done limited work with web sockets but I think the reload button is a good enough option, so web sockets aren't worth it, unless we really want the pages to update content without any user interaction. @m4rk055 thoughts?

**Comment by m4rk055** [comment]
Agree, web sockets are not worth it in this case. Users won't spend much time on the page (and in the future, they will get an email message about the request being finished).
Option (2) sounds good to me.
