### ISSUE TITLE
All checkbox and icons not visible in demo

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#97]
![image (1)](https://user-images.githubusercontent.com/45305362/188492153-9688b2d5-d800-4a42-9cd3-5cf120362a19.png)
![Screenshot from 2022-09-05 19-20-39](https://user-images.githubusercontent.com/45305362/188494723-777589b8-4b19-44f8-9bd2-728e459f5c9d.png)

Fix this while addressing #88. We need two functionalities:
1. The ability to render icons from some library (i.e. font awesome or material)
2. The ability to use our own customs svgs

**Comment by milstan** [comment]
The arrow to expand is also not visible. When I gues where the arrow migh be, and click ther, it expands. Then I can also guess the place of the checkbox and unccheck all.
